version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8000:8080"
    volumes:
      - ./backend/src:/var/www
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: lending
      MYSQL_ROOT_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: password
      MEMORY_LIMIT: 512M
      UPLOAD_LIMIT: 512M
    ports:
      - "8080:80"
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend/src/app:/app
    command: "yarn dev"
    ports:
      - 3000:3000

volumes:
  mysql-volume:
